######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 22 14:37:01 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myqtc1.h YJSQLite.h /arm2410cl/sqlite/sqlite/sqlite3.h
FORMS += untitled.ui
SOURCES += main.cpp myqtseclect.cpp YJSQLite.c
QT+=sql

