######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 25 17:22:28 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gps.h \
           message.h \
           myqtc1.h \
           YJSQLite.h \
           /arm2410cl/sqlite/sqlite/sqlite3.h
FORMS += message.ui untitled.ui
SOURCES += main.cpp myqtseclect.cpp
QT += webkit
