######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 23 16:22:54 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myqtc1.h YJSQLite.h /arm2410cl/sqlite/sqlite/sqlite3.h
FORMS += message.ui untitled.ui
SOURCES += main.cpp myqtseclect.cpp
